name: Publish Docker image
on:
  push:
    branches: master

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            kounoike/slack-to-kibela-emoji-syncer:latest
            kounoike/slack-to-kibela-emoji-syncer:1.0.0
            ghcr.io/kounoike/slack-to-kibela-emoji-syncer:latest
            ghcr.io/kounoike/slack-to-kibela-emoji-syncer:1.0.0